### ISSUE TITLE
Forced humanity and missing bracket

### ISSUE THREAD

**Issue by DeltaPony** [icomrade/icomradeHiveEpoch#2]
Hello, i have an issue, Hive forces humanity for database fixed to 2500 value, and if there is an issue where it has missing bracket in that Object_key_.sqf

function streamObjects

if (_srvObjects.size() == 1) {
  ofs << writeVal;
  ofs << "];";
}

needs to be

if (_srvObjects.size() == 1) {
  ofs << "[";
  ofs << writeVal;
  ofs << "];";
}

and in 

SqlCharDataSource::fetchCharacterInitial and SqlCharDataSource::fetchCharacterDetails

int humanity = 2500; 

should be

int humanity = 0;

or just not forced because its already specified by .sql file of database

i am having issues with building the source so i am asking for your help with this issue

**Comment by icomrade** [comment]
https://github.com/icomrade/icomradeHiveEpoch/blob/master/Hive/Source/HiveLib/HiveExtApp.cpp#L376-L393

I see a possible issue with the design of this logic where there is no data in the DB. I think the proposed change may create more issues, but the logic as is will need to change and I will do so. Thanks for pointing that out.


However, I do not see an issue with using 2500 to initialize the humanity variable in the specified function nor do I see a reason to uninitialize it.

- 2500 is the default value when creating a new character, so it is really the only value that makes sense to initialize the variable.
- if we leave the humanity variable uninitialized then we will end up with an unpredictable value should loading from the SQL DB fail.
